spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/test?characterEncoding=utf8&serveTimezone=Asia/shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #只返回不为null的数据
  jackson:
    default-property-inclusion: non_null
  # 邮箱发送人配置
  mail:
    host: smtp.qq.com
    username: 1954635917@qq.com
    password: waqvuysnbzjijjbf
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false # QQ邮箱不支持 STARTTLS
          connectiontimeout: 5000 # 连接超时时间，单位毫秒
          timeout: 5000 # 超时时间，单位毫秒
          writetimeout: 5000 # 写入超时时间，单位毫秒

# 设置 Mybatis 的 xml 保存路径
mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  configuration: # 配置打印 MyBatis 执行的 SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8888

jwt:
  secret: hello
  expire: 7200