spring:
  application:
    name: SpringSecurityBase
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
#  global-config:

  mapper-locations: classpath:com/example/springsecuritybase/modules/**/*.xml

jwt:
  secret: HelloWorld
  expiration: 1 # 1天过期

logging:
  level:
    org:
      springframework:
        security: debug

