server:
  port: 6666
  servlet:
    context-path: /api
spring:
  application:
    name: SpringSecurityBase
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc: #前端传参，字符串转日期类型
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss

  main:
    banner-mode: off

mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: isDeleted
      logic-not-delete-value: false
      logic-delete-value: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/example/springsecuritybase/modules/**/*.xml



jwt:
  secret: HelloWorld
  expiration: 1 # 1天过期

logging:
  level:
    org:
      springframework:
        security: debug
